name: Trigger CI

on:
  workflow_dispatch:   # HTML button will call this workflow

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Node.js CI
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GHA }}   # ðŸ‘ˆ secret stored in repo settings
          repository: marcoshioka/pages-test
          event-type: run-ci
          client-payload: '{"ref": "main"}'
